baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'CHIENLIN'
theme = 'hugo-coder'
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 20

[markup.highlight]
style = "onedark"

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "CHIENLIN"
info = ["Software Developer"]
description = "A personal blog about development, productivity, and technology"
keywords = "blog,developer,personal"
avatarURL = "images/me.jpg"

faviconSVG = "images/favicon-32x32.svg"
favicon_32 = "images/favicon-32x32.svg"
favicon_16 = "images/favicon-16x16.svg"
touchIcon = "images/apple-touch-icon.svg"

since = 2025

enableTwemoji = true

colorScheme = "light"
hideColorSchemeToggle = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/Risusdan/"
[[params.social]]
name = "Gitlab"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/daniel-su-73627a1a7/"

[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[menu.main]]
name = "Tool"
weight = 2
url = "tools/"

[[menu.main]]
name = "C++"
weight = 3
url = "cpp/"

[[menu.main]]
name = "Categories"
weight = 4
url = "categories/"

[[menu.main]]
name = "Tags"
weight = 5
url = "tags/"

[[menu.main]]
name = "About"
weight = 6
url = "about/"
